package constants;

public enum MessageType {
	CONNECTION_REQUEST,
	CONNECTION_ACCEPTED,
	GET_PREDECESSOR,
	GET_PREDECESSOR_RESPONSE,
	FIND_PREDECESSOR,
	FIND_PREDECESSOR_RESPONSE,
	GET_SUCCESSOR,
	GET_SUCCESSOR_RESPONSE,
	FIND_SUCCESSOR,
	FIND_SUCCESSOR_RESPONSE,
	TRANSFER_DATA_REQUEST,
	TRANSFER_DATA_RESPONSE,
	TRANSFER_DATA_ACK,
	PUT,
	PUT_RESPONSE,
	GET,
	GET_RESPONSE,
	NOTIFY
}
